# Runs weekly or after every push to all branches to validate indexing against staging/production environments

trigger:
  branches:
    include: ["main", "*"]
  paths:
    exclude: ["doc", "*.md"]

schedules:
- cron: "0 15 * * Wed" # Wed @ 8 or 9 AM Mountain Time (depending on DST)
  displayName: Weekly Staging Environment Validation Run
  branches:
    include:
    - main
  always: true

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: RichCodeNavIndexer@0
  displayName: Rich Code Navigation Upload to Staging
  inputs:
    languages: 'csharp,typescript,java,cpp'
    githubServiceConnection: 'mohaimenhasan'
    environment: internal
    isPrivateFeed: false
  continueOnError: false

